### ISSUE TITLE
mapping todo list - 20190126

### ISSUE THREAD

**Issue by zy410419243** [zy410419243/zy410419243.github.io#3]
- [x] 新建 `mapping` https://github.com/zy410419243/zy410419243.github.io/pull/10
1. server 处理 `/new`。需要尝试
2. server 收到 layout 后，往缩略图映射文件夹里存个文件，也往 layout 文件夹里存个。文件名用 `md5` 生成，需要保持一致
3. ~~生成缩略图快照并~~保存，~~按日期分组，精确到天~~，用上面的 `md5` 命名。需要尝试

- [x] 路由 `/` 显示已存在 `mapping` 的缩略图 https://github.com/zy410419243/zy410419243.github.io/pull/4
1. 建个文件夹放缩略图映射数据，用作 web 缩略图显示 -> id、标题、缩略图片地址、移入时文本、创建及修改时间
2. 建个文件夹放 layout 数据，用作 web `mapping` 详情显示 -> `mini-xmid` 原样保存
3. server 启动前，扫描缩略图映射文件夹内数据，生成一个 json 文件
4. server 处理 `/`，返回 `mapping` 对应的 html
5. web 请求 json 并显示
6. 右键缩略图显示菜单，上面加俩 `Icon`，一个修改，一个删除。后续需要额外文件用作配置，但现在先放代码里

- [x] 修改 `mapping`  https://github.com/zy410419243/zy410419243.github.io/pull/8
1. web 跳到 `/id`
2. server 处理 `/id`
3. 保存时直接覆盖对应的三个文件，所以提交时需要新建时的所有数据，还需要额外的 id，时间戳由 server 控制

- [x] 删除 `mapping` https://github.com/zy410419243/zy410419243.github.io/pull/9
1. ~~web 显示确定框~~ 都右键了那肯定是要删的
2. server 删除缩略图、layout 和缩略图映射

**Comment by zy410419243** [comment]
想了半天，server 在我认知范围里没法把用 webpack 打包出来的文件做按需加载，所以暂时把所有模块都堆在一起，前端控制状态，server 仅处理文件操作

**Comment by zy410419243** [comment]
本地 fetch `mapping.json` 会乱码，但服务器上不会

**Comment by zy410419243** [comment]
又想了半天，路由用 js 的 router 似乎没问题，服务器上是静态的文件，碰到问题的是本地

也就是说只要在本地服务跑起来之前把路由生成出来就可以脱离 server 的路由了

**Comment by zy410419243** [comment]
需要查查 `react-router` 是否能实现热加载，新建时因为 `mapping.json` 被写入了，但 router 并没有更新，于是跳转时就会白屏

现在是用 `/new` hack 了
